name: Manage MultiJuicer
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action'
        required: true
        type: choice
        options:
          - new
          - up
          - down
          - wipe

permissions:
  id-token: write
  contents: read

jobs:
  manage-multijuicer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Manage MultiJuicer'
        run: |
          chmod +x ./manage-multijuicer.sh
          source .env
          ./manage-multijuicer.sh "$ACTION"
        env:
          ACTION: ${{ inputs.action }}
